### PR TITLE
Refactor/ts

### PR DESCRIPTION
**Pull request by peterblazejewicz**
@manishkumar-tudip  @travist
 
I've made this PR `cause I'm fan of the service and I've found a problem using NG 2 published NPM version and even building and running this repo locally:
https://gist.github.com/peterblazejewicz/68aa8c509c4c7021fec41944ac885253
https://gist.github.com/peterblazejewicz/8c9f615e68500f6427e36d3a8e740ae0

This PR should be probably split into many single commits, but I'd rather to either get it merged or rejected but with your inputs. You could get PR locally and verify if suggested changes are OK.
Please remember then when running PR locally you would need to `rm -rf node_modules typings` first

Update TypeScript compilation implementation
This commit:
- updates TypeScript to 2.0.10 as used in Angular 2.4.*
- introduces NPM based @types into TypeScript toolchain
- removes traces of Typings both from toolchain from package.json
and from source files references to avoid double rerences TS errors
- moves all TypeScript compilation task into tsconfig.json based
workflow as Gulp based task could not generate expected output -
the moved task to NPM script now correctly renders transpiled JS file
source map and type definition for TypeScript source file
- the main template file `bootstrap.tpl.ts` has been renamed to
`bootstrap.templates.tpl.ts` and excluded from TS compilation steps
by configuration. At the same time other TS modules no longer reference
template (.tpl.ts) module - but their reference has been changed to
generated file `bootstrap.templates.ts` so now TSC compiler no longer
emits errors about invalid declarations in template file
- some small modules imports have been fixed in example/ folder removing
extensions from referenced filenames
- the zone.js version has been updated to 0.7.4 (as the one used in
Angular 2.4.*)
- unused Gulp modules have been removed from NPM package references
- the TypeScript reference in package.json has been fixed to 2.0.10
to avoid background installation of TypeScript 2.1.4 - which could
brake a lot of things, for example with WebPack and Karma tasks:
https://git.io/vMWY6

Build distribution files
The build is now managed by running:

`npm run build`

The Gulp task (ones left in `gulpfile.js`) has been mapped
to NPM task:
gulp clear > npm run clean
gulp templates > npm run templates

The NPM package contains now following scripts:

```bash
Lifecycle scripts included in ng2-formio:
  start
    webpack-dev-server --inline --progress --content-base /example
--port 8080
  test
    karma start

available via `npm run-script`:
  build
    npm run clean && npm run templates && npm run typescript
  clean
    gulp clean
  templates
    gulp templates
  typescript
    tsc
```

Thanks!

### CODE REVIEW

**Comment by travist** [comment]
@peterblazejewicz this is amazing and I applaud your effort. From looking through these changes, it is clear you know what you are doing. I am going to review these, and pull them in and do some quick tests. If all goes well, then we will be glad to bring in this massive contribution.

Thanks again!

**Comment by travist** [comment]
Just ran a quick test and it looks great!  Thanks again!!

**Comment by peterblazejewicz** [comment]
@travist 
Do you folks have some plans for this module futher changes, fixes, etc? 
I've planned to use it as part of OSS license in a project and would be glad to help you with this part of form.io content.

Thanks!

**Comment by travist** [comment]
Hello @peterblazejewicz 

Yes, we do have plans for this in the future, but from a "renderer" perspective, this is pretty feature complete. What is coming next are some helper libraries, which would end up being separate classes attached to this repo. We welcome your participation in helping us develop this renderer. If you have anything in mind on what you would like to introduce, then please let us know and we would be happy to work with you!

Again, thank you for your efforts!

Travis.

**Comment by peterblazejewicz** [comment]
I'll write sample with `angular-cli` (other most frequently used tooling for ng 2) to show how current version fails to build and compile (at least I have a problems). We are using `angular-cli` as guided development schema. Also I'll look here and there in the source code to get accustomed (I really like the idea of the service itself and I've listened to AiA podcast eposide with you folks
Thanks!

**Pull request merged**
